# Regla para la API. Debe ir primero para tener prioridad sobre la ruta "/*".
[[redirects]]
  from = "/api/*"
  to = "https://nayenailsbackend.onrender.com/api/:splat"
  status = 200

# Declaración de la Edge Function.
# Se ejecutará en todas las rutas que no coincidan con la regla de la API.
[[edge_functions]]
  path = "/*"
  function = "preview-proxy"

# Regla de fallback para la SPA.
# Si la Edge Function no reescribe la URL (porque no es un bot),
# esta regla se asegura de que el usuario vea la aplicación de React.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200